###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: symfony-webserver
      working_dir: /application
      volumes:
        - ./src:/application
        - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8081:80"

    php-fpm:
      build: infra/php-fpm
      container_name: symfony-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./infra/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    mongodb:
      image: mongo
      container_name: symfony-mongodb
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
        - MONGO_DATA_DIR=/data/db
      volumes:
        - ./infra/data/db:/data/db
      ports:
        - "27017:27017"